# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Team.create({:name => "Team SoloMid", :wins => 21, :losses => 7, :region => "NA"})
Team.create({:name => "Curse", :wins => 19, :losses => 9, :region => "NA"})
Team.create({:name => "Team Dignitas", :wins => 17, :losses => 11, :region => "NA"})
Team.create({:name => "Counter Logic Gaming", :wins => 13, :losses => 15, :region => "NA"})
Team.create({:name => "Team Vulcun", :wins => 12, :losses => 16, :region => "NA"})
Team.create({:name => "Good Game University", :wins => 11, :losses => 17, :region => "NA"})
Team.create({:name => "Team MRN", :wins => 10, :losses => 18, :region => "NA"})
Team.create({:name => "compLexity Gaming", :wins => 9, :losses => 19, :region => "NA"})
Team.create({:name => "Fnatic", :wins => 22, :losses => 6, :region => "EU"})
Team.create({:name => "Gambit Gaming", :wins => 21, :losses => 7, :region => "EU"})
Team.create({:name => "SK Gaming", :wins => 17, :losses => 11, :region => "EU"})
Team.create({:name => "Evil Geniuses", :wins => 15, :losses => 13, :region => "EU"})
Team.create({:name => "Copenhagen Wolves", :wins => 13, :losses => 15, :region => "EU"})
Team.create({:name => "against All authority", :wins => 10, :losses => 18, :region => "EU"})
Team.create({:name => "GIANTS! Gaming", :wins => 8, :losses => 20, :region => "EU"})
Team.create({:name => "DragonBorns", :wins => 6, :losses => 22, :region => "EU"})

Player.create({:p_name => 'Dyrus', :t_name => 'Team SoloMid', :role => 'Top', :team_id => 1})
Player.create({:p_name => 'Reginald', :t_name => 'Team SoloMid', :role => 'Mid', :team_id => 1})
Player.create({:p_name => 'WildTurtle', :t_name => 'Team SoloMid', :role => 'AD', :team_id => 1})
Player.create({:p_name => 'TheOddOne', :t_name => 'Team SoloMid', :role => 'Jungle', :team_id => 1})
Player.create({:p_name => 'Xpecial', :t_name => 'Team SoloMid', :role => 'Support', :team_id => 1})
Player.create({:p_name => 'HotshotGG', :t_name => 'Counter Logic Gaming', :role => 'Top', :team_id => 4})
Player.create({:p_name => 'Link', :t_name => 'Counter Logic Gaming', :role => 'Mid', :team_id => 4})
Player.create({:p_name => 'Doublelift', :t_name => 'Counter Logic Gaming', :role => 'AD', :team_id => 4})
Player.create({:p_name => 'Chauster', :t_name => 'Counter Logic Gaming', :role => 'Jungle', :team_id => 4})
Player.create({:p_name => 'Aphromoo', :t_name => 'Counter Logic Gaming', :role => 'Support', :team_id => 4})
Player.create({:p_name => 'Wickd', :t_name => 'Evil Geniuses', :role => 'Top', :team_id => 12})
Player.create({:p_name => 'Froggen', :t_name => 'Evil Geniuses', :role => 'Mid', :team_id => 12})
Player.create({:p_name => 'Yellowpete', :t_name => 'Evil Geniuses', :role => 'AD', :team_id => 12})
Player.create({:p_name => 'Snoopeh', :t_name => 'Evil Geniuses', :role => 'Jungle', :team_id => 12})
Player.create({:p_name => 'Krepo', :t_name => 'Evil Geniuses', :role => 'Support', :team_id => 12})

Match.create({:match_date => '06/12/2013', :match_time => "4:00", :purple_team => "Team Coast", :blue_team => "Team SoloMid", :played => false})
Match.create({:match_date => '06/12/2013', :match_time => "5:00", :purple_team => "Curse", :blue_team => "Team Vulcan", :played => false})
Match.create({:match_date => '06/12/2013', :match_time => "6:00", :purple_team => "Team Dignatas", :blue_team => "Cloud 9", :played => false})
Match.create({:match_date => '06/12/2013', :match_time => "7:00", :purple_team => "Counter Logic Gaming", :blue_team => "Velocity", :played => false})
Match.create({:match_date => '06/12/2013', :match_time => "8:00", :purple_team => "Team SoloMid", :blue_team => "Cloud 9", :played => false})
Match.create({:match_date => '06/12/2013', :match_time => "9:00", :purple_team => "Team Coast", :blue_team => "Team Vulcan", :played => false})

PlayerSplit.create({:player_id => 1, :split_id => 2, :role => 'Top', :kills => 7, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 2, :split_id => 2, :role => 'Mid', :kills => 2, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 3, :split_id => 2, :role => 'AD', :kills => 5, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 4, :split_id => 2, :role => 'Jungle', :kills => 1, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 5, :split_id => 2, :role => 'Support', :kills => 6, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 6, :split_id => 2, :role => 'Top', :kills => 4, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 7, :split_id => 2, :role => 'Mid', :kills => 5, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 8, :split_id => 2, :role => 'AD',  :kills => 3, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 9, :split_id => 2, :role => 'Jungle', :kills => 7, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 10, :split_id => 2, :role => 'Support', :kills => 2, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 11, :split_id => 2, :role => 'Top', :kills => 1, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 12, :split_id => 2, :role => 'Mid', :kills => 6, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 13, :split_id => 2, :role => 'AD', :kills => 2, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 14, :split_id => 2, :role => 'Jungle', :kills => 5, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})
PlayerSplit.create({:player_id => 15, :split_id => 2, :role => 'Support', :kills => 8, :deaths => 2, :assists => 6, :cs => 250, :gold => 50000})

Season.create({:season_name => 'Season 3'})

Split.create({:split_name => 'Spring Split', :season_id => 1})
Split.create({:split_name => 'Summer Split', :season_id => 1})


